INSERT INTO Expenses VALUES (1, 55,00, 'T SHIRT', 'SHOPPING', GETDATE());
INSERT INTO Expenses VALUES (2, 10,00, 'Train to Minsk', 'TRANSPORT', GETDATE());
INSERT INTO Expenses VALUES (3, 110,00, 'Train to Orsha', 'TRANSPORT', GETDATE());
INSERT INTO Expenses VALUES (4, 99,50, 'Fish oil', 'HEALTH', GETDATE());
INSERT INTO Expenses VALUES (5, 33,20, 'Dinner', 'RESTAURANT', GETDATE());
INSERT INTO Expenses VALUES (6, 6,50, 'Noodles', 'GROCERIES', GETDATE());
INSERT INTO Expenses VALUES (7, 0,80, 'Gum', 'GROCERIES', GETDATE());
INSERT INTO Expenses VALUES (8, 220,80, 'SHOES', 'SHOPPING', GETDATE());